

/***************************** Include Files *******************************/
#include "Exin_TIMER.h"
#include "xil_io.h"

/************************** Function Definitions ***************************/

void EXIN_TIMER_Init()
{
		EXIN_TIMER_mWriteReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG1_OFFSET, 0x07);
		EXIN_TIMER_mWriteReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG1_OFFSET, 0x00);
		EXIN_TIMER_mWriteReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG2_OFFSET, 0x07);	
}

void EXIN_TIMER_Delayus(long int data)
{
		static long int din;
		din = data * 50;
		EXIN_TIMER_mWriteReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG0_OFFSET, din);
		EXIN_TIMER_mWriteReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG1_OFFSET, 0x05);
		EXIN_TIMER_mWriteReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG1_OFFSET, 0x00);
	
		while( (EXIN_TIMER_mReadReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG8_OFFSET)) == 0 );
		
		EXIN_TIMER_mWriteReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG1_OFFSET, 0x04);
		EXIN_TIMER_mWriteReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG1_OFFSET, 0x00);
}

int EXIN_TIMER_Read(Clock_enum sel)
{
	switch(sel)
	{
		case(TIME_us):
		{
			return EXIN_TIMER_mReadReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG7_OFFSET);
		}
		
		case(TIME_ms):
		{
			return EXIN_TIMER_mReadReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG6_OFFSET);
		}
		
		case(TIME_sec):
		{
			return EXIN_TIMER_mReadReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG5_OFFSET);
		}
		
		case(TIME_min):
		{
			return EXIN_TIMER_mReadReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG4_OFFSET);
		}
		
		case(TIME_hour):
		{
			return EXIN_TIMER_mReadReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG3_OFFSET);
		}
	}
	
	return 0;
}
	
int EXIN_TIMER_GetTime()
{
	return EXIN_TIMER_mReadReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG3_OFFSET) * 3600 + EXIN_TIMER_mReadReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG4_OFFSET) * 60 + EXIN_TIMER_mReadReg(XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR, EXIN_TIMER_S0_AXI_SLV_REG5_OFFSET);
}
		
		