# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: V:/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7.xdc

# XDC: V:/hardware/m3_for_arty_a7/constraints/m3_for_arty_a7_impl.xdc

# Block Designs: V:/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7 || ORIG_REF_NAME==m3_for_arty_a7} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/m3_for_arty_a7_proc_sys_reset_DAPLink_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_interconnect_aresetn_0/m3_for_arty_a7_i_interconnect_aresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_interconnect_aresetn_0 || ORIG_REF_NAME==m3_for_arty_a7_i_interconnect_aresetn_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_peripheral_aresetn1_0/m3_for_arty_a7_i_peripheral_aresetn1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_peripheral_aresetn1_0 || ORIG_REF_NAME==m3_for_arty_a7_i_peripheral_aresetn1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_sysresetn_or_0/m3_for_arty_a7_i_sysresetn_or_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_sysresetn_or_0 || ORIG_REF_NAME==m3_for_arty_a7_i_sysresetn_or_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_inv_dbgresetn_0/m3_for_arty_a7_i_inv_dbgresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_inv_dbgresetn_0 || ORIG_REF_NAME==m3_for_arty_a7_i_inv_dbgresetn_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_i_inv_sysresetn1_0/m3_for_arty_a7_i_inv_sysresetn1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_inv_sysresetn1_0 || ORIG_REF_NAME==m3_for_arty_a7_i_inv_sysresetn1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_1_0/m3_for_arty_a7_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_1_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0/m3_for_arty_a7_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_bram_ctrl_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_interconnect_0_0/m3_for_arty_a7_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_interconnect_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_interconnect_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xbar_0 || ORIG_REF_NAME==m3_for_arty_a7_xbar_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/m3_for_arty_a7_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_blk_mem_gen_0_0 || ORIG_REF_NAME==m3_for_arty_a7_blk_mem_gen_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_interconnect_0_1/m3_for_arty_a7_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_interconnect_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_interconnect_0_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_1/m3_for_arty_a7_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xbar_1 || ORIG_REF_NAME==m3_for_arty_a7_xbar_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_single_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_single_spi_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_protocol_convert_0_0/m3_for_arty_a7_axi_protocol_convert_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_protocol_convert_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_protocol_convert_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_DAPLink_to_Arty_shield_0_0/m3_for_arty_a7_DAPLink_to_Arty_shield_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_DAPLink_to_Arty_shield_0_0 || ORIG_REF_NAME==m3_for_arty_a7_DAPLink_to_Arty_shield_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_tri_io_buf_0_0/m3_for_arty_a7_tri_io_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_tri_io_buf_0_0 || ORIG_REF_NAME==m3_for_arty_a7_tri_io_buf_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_0_0/m3_for_arty_a7_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_0_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconcat_1_0/m3_for_arty_a7_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_1_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_1_1/m3_for_arty_a7_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_1_1 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_1_1} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/m3_for_arty_a7_Cortex_M3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Cortex_M3_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Cortex_M3_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_ADC0832_0_0/m3_for_arty_a7_Exin_ADC0832_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_ADC0832_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_ADC0832_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_HeartFre2_0_0/m3_for_arty_a7_Exin_HeartFre2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_HeartFre2_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_HeartFre2_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_MAXMIN2_0_0/m3_for_arty_a7_Exin_MAXMIN2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_MAXMIN2_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_MAXMIN2_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_dht11_0_0/m3_for_arty_a7_Exin_dht11_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_dht11_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_dht11_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_MPU6050_GYXX_0_0/m3_for_arty_a7_Exin_MPU6050_GYXX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_MPU6050_GYXX_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_MPU6050_GYXX_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_StepCounter_deb_0_0/m3_for_arty_a7_Exin_StepCounter_deb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_StepCounter_deb_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_StepCounter_deb_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_breath_led_0_0/m3_for_arty_a7_breath_led_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_breath_led_0_0 || ORIG_REF_NAME==m3_for_arty_a7_breath_led_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_Timer_0_0/m3_for_arty_a7_Exin_Timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_Timer_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_Timer_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_beep_0_0/m3_for_arty_a7_Exin_beep_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_beep_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_beep_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_1_0/m3_for_arty_a7_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_IO_printer_0_0/m3_for_arty_a7_Exin_IO_printer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_IO_printer_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_IO_printer_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_2_0/m3_for_arty_a7_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_2_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_2_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_clk_wizard_0_0/m3_for_arty_a7_Exin_clk_wizard_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_clk_wizard_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_clk_wizard_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_clk_wizard_1_0/m3_for_arty_a7_Exin_clk_wizard_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_clk_wizard_1_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_clk_wizard_1_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_0_0/m3_for_arty_a7_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_0_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xlconstant_2_0/m3_for_arty_a7_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_2_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_2_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_noliner2_0_0/m3_for_arty_a7_Exin_noliner2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_noliner2_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_noliner2_0_0} -quiet] -quiet

# IP: V:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Exin_HMITX_0_0/m3_for_arty_a7_Exin_HMITX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Exin_HMITX_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Exin_HMITX_0_0} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_tier2_xbar_0_0/m3_for_arty_a7_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_tier2_xbar_0_0 || ORIG_REF_NAME==m3_for_arty_a7_tier2_xbar_0_0} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_tier2_xbar_1_0/m3_for_arty_a7_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_tier2_xbar_1_0 || ORIG_REF_NAME==m3_for_arty_a7_tier2_xbar_1_0} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_tier2_xbar_2_0/m3_for_arty_a7_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_tier2_xbar_2_0 || ORIG_REF_NAME==m3_for_arty_a7_tier2_xbar_2_0} -quiet] -quiet

# IP: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_0/m3_for_arty_a7_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_0 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_0} -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/m3_for_arty_a7_proc_sys_reset_DAPLink_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/m3_for_arty_a7_proc_sys_reset_DAPLink_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_DAPLink_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_DAPLink_0/m3_for_arty_a7_proc_sys_reset_DAPLink_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_clk_wiz_0_0 || ORIG_REF_NAME==m3_for_arty_a7_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_clk_wiz_0_0/m3_for_arty_a7_clk_wiz_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0/m3_for_arty_a7_axi_bram_ctrl_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_0/m3_for_arty_a7_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_1_0/m3_for_arty_a7_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_0/m3_for_arty_a7_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/m3_for_arty_a7_blk_mem_gen_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_xbar_1/m3_for_arty_a7_xbar_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_single_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_single_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_single_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_single_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_single_spi_0_0/m3_for_arty_a7_axi_single_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_single_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_single_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_quad_spi_0_1/m3_for_arty_a7_axi_quad_spi_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_xip_quad_spi_0_0/m3_for_arty_a7_axi_xip_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_xip_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_1/m3_for_arty_a7_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_1 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_protocol_convert_0_0/m3_for_arty_a7_axi_protocol_convert_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/m3_for_arty_a7_Cortex_M3_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Cortex_M3_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Cortex_M3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_1_0/m3_for_arty_a7_axi_uartlite_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_1_0/m3_for_arty_a7_axi_uartlite_1_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_uartlite_1_0/m3_for_arty_a7_axi_uartlite_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_1_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_2_0/m3_for_arty_a7_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_2_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_2_0/m3_for_arty_a7_axi_gpio_2_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_axi_gpio_2_0/m3_for_arty_a7_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_2_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_tier2_xbar_0_0/m3_for_arty_a7_tier2_xbar_0_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_tier2_xbar_1_0/m3_for_arty_a7_tier2_xbar_1_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_tier2_xbar_2_0/m3_for_arty_a7_tier2_xbar_2_0_ooc.xdc

# XDC: v:/hardware/m3_for_arty_a7/block_diagram/ip/m3_for_arty_a7_auto_pc_0/m3_for_arty_a7_auto_pc_0_ooc.xdc

# XDC: V:/hardware/m3_for_arty_a7/block_diagram/m3_for_arty_a7_ooc.xdc
