#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 0U

/* Definitions for peripheral CORTEX_M3_0 */
#define XPAR_CORTEX_M3_0_CPU_CLK_FREQ_HZ 0


/******************************************************************/

/* Canonical definitions for peripheral CORTEX_M3_0 */
#define XPAR_CPU_CORTEXM3_0_CPU_CLK_FREQ_HZ 0


/******************************************************************/

#define STDIN_BASEADDRESS 0x40100000
#define STDOUT_BASEADDRESS 0x40100000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_ARM
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver EXIN_ADC0832 */
#define XPAR_EXIN_ADC0832_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_ADC0832_0 */
#define XPAR_EXIN_ADC0832_0_DEVICE_ID 0
#define XPAR_EXIN_ADC0832_0_S0_AXI_BASEADDR 0x44A00000
#define XPAR_EXIN_ADC0832_0_S0_AXI_HIGHADDR 0x44A0FFFF


/******************************************************************/

/* Definitions for driver EXIN_HMITX */
#define XPAR_EXIN_HMITX_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_HMITX_0 */
#define XPAR_EXIN_HMITX_0_DEVICE_ID 0
#define XPAR_EXIN_HMITX_0_S0_AXI_BASEADDR 0x44AB0000
#define XPAR_EXIN_HMITX_0_S0_AXI_HIGHADDR 0x44ABFFFF


/******************************************************************/

/* Definitions for driver EXIN_HEARTFRE2 */
#define XPAR_EXIN_HEARTFRE2_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_HEARTFRE2_0 */
#define XPAR_EXIN_HEARTFRE2_0_DEVICE_ID 0
#define XPAR_EXIN_HEARTFRE2_0_S0_AXI_BASEADDR 0x44A10000
#define XPAR_EXIN_HEARTFRE2_0_S0_AXI_HIGHADDR 0x44A1FFFF


/******************************************************************/

/* Definitions for driver EXIN_IO_PRINTER */
#define XPAR_EXIN_IO_PRINTER_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_IO_PRINTER_0 */
#define XPAR_EXIN_IO_PRINTER_0_DEVICE_ID 0
#define XPAR_EXIN_IO_PRINTER_0_S0_AXI_BASEADDR 0x44A90000
#define XPAR_EXIN_IO_PRINTER_0_S0_AXI_HIGHADDR 0x44A9FFFF


/******************************************************************/

/* Definitions for driver EXIN_MAXMIN2 */
#define XPAR_EXIN_MAXMIN2_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_MAXMIN2_0 */
#define XPAR_EXIN_MAXMIN2_0_DEVICE_ID 0
#define XPAR_EXIN_MAXMIN2_0_S0_AXI_BASEADDR 0x44A20000
#define XPAR_EXIN_MAXMIN2_0_S0_AXI_HIGHADDR 0x44A2FFFF


/******************************************************************/

/* Definitions for driver EXIN_MPU6050_GYXX */
#define XPAR_EXIN_MPU6050_GYXX_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_MPU6050_GYXX_0 */
#define XPAR_EXIN_MPU6050_GYXX_0_DEVICE_ID 0
#define XPAR_EXIN_MPU6050_GYXX_0_S00_AXI_BASEADDR 0x44A40000
#define XPAR_EXIN_MPU6050_GYXX_0_S00_AXI_HIGHADDR 0x44A4FFFF


/******************************************************************/

/* Definitions for driver EXIN_STEPCOUNTER_DEBUG */
#define XPAR_EXIN_STEPCOUNTER_DEBUG_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_STEPCOUNTER_DEB_0 */
#define XPAR_EXIN_STEPCOUNTER_DEB_0_DEVICE_ID 0
#define XPAR_EXIN_STEPCOUNTER_DEB_0_S00_AXI_BASEADDR 0x44A50000
#define XPAR_EXIN_STEPCOUNTER_DEB_0_S00_AXI_HIGHADDR 0x44A5FFFF


/******************************************************************/

/* Definitions for driver EXIN_TIMER */
#define XPAR_EXIN_TIMER_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_TIMER_0 */
#define XPAR_EXIN_TIMER_0_DEVICE_ID 0
#define XPAR_EXIN_TIMER_0_S0_AXI_BASEADDR 0x44A70000
#define XPAR_EXIN_TIMER_0_S0_AXI_HIGHADDR 0x44A7FFFF


/******************************************************************/

/* Definitions for driver EXIN_BEEP */
#define XPAR_EXIN_BEEP_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_BEEP_0 */
#define XPAR_EXIN_BEEP_0_DEVICE_ID 0
#define XPAR_EXIN_BEEP_0_S0_AXI_BASEADDR 0x44A80000
#define XPAR_EXIN_BEEP_0_S0_AXI_HIGHADDR 0x44A8FFFF


/******************************************************************/

/* Definitions for driver EXIN_DHT11 */
#define XPAR_EXIN_DHT11_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_DHT11_0 */
#define XPAR_EXIN_DHT11_0_DEVICE_ID 0
#define XPAR_EXIN_DHT11_0_S0_AXI_BASEADDR 0x44A30000
#define XPAR_EXIN_DHT11_0_S0_AXI_HIGHADDR 0x44A3FFFF


/******************************************************************/

/* Definitions for driver EXIN_NOLINER2 */
#define XPAR_EXIN_NOLINER2_NUM_INSTANCES 1

/* Definitions for peripheral EXIN_NOLINER2_0 */
#define XPAR_EXIN_NOLINER2_0_DEVICE_ID 0
#define XPAR_EXIN_NOLINER2_0_S0_AXI_BASEADDR 0x44AA0000
#define XPAR_EXIN_NOLINER2_0_S0_AXI_HIGHADDR 0x44AAFFFF


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_DEVICE_ID 0U
#define XPAR_AXI_BRAM_CTRL_0_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_0_ECC 0U
#define XPAR_AXI_BRAM_CTRL_0_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_0_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR 0x60000000U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR 0x60001FFFU
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/******************************************************************/

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_BRAM_0_DEVICE_ID XPAR_AXI_BRAM_CTRL_0_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_0_WRITE_ACCESS 0U
#define XPAR_BRAM_0_BASEADDR 0x60000000U
#define XPAR_BRAM_0_HIGHADDR 0x60001FFFU
#define XPAR_BRAM_0_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_0_CTRL_HIGHADDR 0xFFFFFFFEU  


/******************************************************************/

/* Definitions for driver BREATH_LED */
#define XPAR_BREATH_LED_NUM_INSTANCES 1

/* Definitions for peripheral BREATH_LED_0 */
#define XPAR_BREATH_LED_0_DEVICE_ID 0
#define XPAR_BREATH_LED_0_S0_AXI_BASEADDR 0x44A60000
#define XPAR_BREATH_LED_0_S0_AXI_HIGHADDR 0x44A6FFFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 4

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_BASEADDR 0x40110000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4011FFFF
#define XPAR_AXI_GPIO_0_DEVICE_ID 0
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 1
#define XPAR_AXI_GPIO_0_IS_DUAL 1


/* Definitions for peripheral AXI_GPIO_1 */
#define XPAR_AXI_GPIO_1_BASEADDR 0x40120000
#define XPAR_AXI_GPIO_1_HIGHADDR 0x4012FFFF
#define XPAR_AXI_GPIO_1_DEVICE_ID 1
#define XPAR_AXI_GPIO_1_INTERRUPT_PRESENT 1
#define XPAR_AXI_GPIO_1_IS_DUAL 1


/* Definitions for peripheral AXI_GPIO_2 */
#define XPAR_AXI_GPIO_2_BASEADDR 0x40040000
#define XPAR_AXI_GPIO_2_HIGHADDR 0x4004FFFF
#define XPAR_AXI_GPIO_2_DEVICE_ID 2
#define XPAR_AXI_GPIO_2_INTERRUPT_PRESENT 1
#define XPAR_AXI_GPIO_2_IS_DUAL 0


/* Definitions for peripheral DAPLINK_IF_0_AXI_GPIO_0 */
#define XPAR_DAPLINK_IF_0_AXI_GPIO_0_BASEADDR 0x40010000
#define XPAR_DAPLINK_IF_0_AXI_GPIO_0_HIGHADDR 0x4001FFFF
#define XPAR_DAPLINK_IF_0_AXI_GPIO_0_DEVICE_ID 3
#define XPAR_DAPLINK_IF_0_AXI_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_DAPLINK_IF_0_AXI_GPIO_0_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_GPIO_0_BASEADDR 0x40110000
#define XPAR_GPIO_0_HIGHADDR 0x4011FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_AXI_GPIO_0_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 1
#define XPAR_GPIO_0_IS_DUAL 1

/* Canonical definitions for peripheral AXI_GPIO_1 */
#define XPAR_GPIO_1_BASEADDR 0x40120000
#define XPAR_GPIO_1_HIGHADDR 0x4012FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_AXI_GPIO_1_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 1
#define XPAR_GPIO_1_IS_DUAL 1

/* Canonical definitions for peripheral AXI_GPIO_2 */
#define XPAR_GPIO_2_BASEADDR 0x40040000
#define XPAR_GPIO_2_HIGHADDR 0x4004FFFF
#define XPAR_GPIO_2_DEVICE_ID XPAR_AXI_GPIO_2_DEVICE_ID
#define XPAR_GPIO_2_INTERRUPT_PRESENT 1
#define XPAR_GPIO_2_IS_DUAL 0

/* Canonical definitions for peripheral DAPLINK_IF_0_AXI_GPIO_0 */
#define XPAR_GPIO_3_BASEADDR 0x40010000
#define XPAR_GPIO_3_HIGHADDR 0x4001FFFF
#define XPAR_GPIO_3_DEVICE_ID XPAR_DAPLINK_IF_0_AXI_GPIO_0_DEVICE_ID
#define XPAR_GPIO_3_INTERRUPT_PRESENT 0
#define XPAR_GPIO_3_IS_DUAL 0


/******************************************************************/

/* Definitions for driver SPI */
#define XPAR_XSPI_NUM_INSTANCES 4U

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_DEVICE_ID 0U
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x40130000U
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x4013FFFFU
#define XPAR_AXI_QUAD_SPI_0_FIFO_DEPTH 256U
#define XPAR_AXI_QUAD_SPI_0_FIFO_EXIST 1U
#define XPAR_AXI_QUAD_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 1U
#define XPAR_AXI_QUAD_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 2U
#define XPAR_AXI_QUAD_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_AXI_QUAD_SPI_0_AXI4_BASEADDR 0U
#define XPAR_AXI_QUAD_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0U

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_SPI_0_DEVICE_ID 0U
#define XPAR_SPI_0_BASEADDR 0x40130000U
#define XPAR_SPI_0_HIGHADDR 0x4013FFFFU
#define XPAR_SPI_0_FIFO_DEPTH 256U
#define XPAR_SPI_0_FIFO_EXIST 1U
#define XPAR_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_0_NUM_SS_BITS 1U
#define XPAR_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_0_SPI_MODE 2U
#define XPAR_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_SPI_0_AXI4_BASEADDR 0U
#define XPAR_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_SPI_0_XIP_MODE 0U
#define XPAR_SPI_0_USE_STARTUP 0U



/* Definitions for peripheral DAPLINK_IF_0_AXI_QUAD_SPI_0 */
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_DEVICE_ID 1U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_BASEADDR 0x40020000U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_HIGHADDR 0x4002FFFFU
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_FIFO_DEPTH 256U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_FIFO_EXIST 1U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_NUM_SS_BITS 1U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_SPI_MODE 2U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_AXI4_BASEADDR 0U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_DAPLINK_IF_0_AXI_QUAD_SPI_0_XIP_MODE 0U

/* Canonical definitions for peripheral DAPLINK_IF_0_AXI_QUAD_SPI_0 */
#define XPAR_SPI_1_DEVICE_ID 1U
#define XPAR_SPI_1_BASEADDR 0x40020000U
#define XPAR_SPI_1_HIGHADDR 0x4002FFFFU
#define XPAR_SPI_1_FIFO_DEPTH 256U
#define XPAR_SPI_1_FIFO_EXIST 1U
#define XPAR_SPI_1_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_1_NUM_SS_BITS 1U
#define XPAR_SPI_1_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_1_SPI_MODE 2U
#define XPAR_SPI_1_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_SPI_1_AXI4_BASEADDR 0U
#define XPAR_SPI_1_AXI4_HIGHADDR 0U
#define XPAR_SPI_1_XIP_MODE 0U
#define XPAR_SPI_1_USE_STARTUP 0U



/* Definitions for peripheral DAPLINK_IF_0_AXI_SINGLE_SPI_0 */
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_DEVICE_ID 2U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_BASEADDR 0x40030000U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_HIGHADDR 0x4003FFFFU
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_FIFO_DEPTH 256U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_FIFO_EXIST 1U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_NUM_SS_BITS 1U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_SPI_MODE 0U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_AXI4_BASEADDR 0U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_DAPLINK_IF_0_AXI_SINGLE_SPI_0_XIP_MODE 0U

/* Canonical definitions for peripheral DAPLINK_IF_0_AXI_SINGLE_SPI_0 */
#define XPAR_SPI_2_DEVICE_ID 2U
#define XPAR_SPI_2_BASEADDR 0x40030000U
#define XPAR_SPI_2_HIGHADDR 0x4003FFFFU
#define XPAR_SPI_2_FIFO_DEPTH 256U
#define XPAR_SPI_2_FIFO_EXIST 1U
#define XPAR_SPI_2_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_2_NUM_SS_BITS 1U
#define XPAR_SPI_2_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_2_SPI_MODE 0U
#define XPAR_SPI_2_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_SPI_2_AXI4_BASEADDR 0U
#define XPAR_SPI_2_AXI4_HIGHADDR 0U
#define XPAR_SPI_2_XIP_MODE 0U
#define XPAR_SPI_2_USE_STARTUP 0U



/* Definitions for peripheral DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0 */
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_DEVICE_ID 3U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_BASEADDR 0x40000000U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_HIGHADDR 0x4000FFFFU
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_FIFO_DEPTH 16U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_FIFO_EXIST 1U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_NUM_SS_BITS 1U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_SPI_MODE 2U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_AXI4_BASEADDR 0x00000000U
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_AXI4_HIGHADDR 0x000FFFFFU
#define XPAR_DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0_XIP_MODE 1U

/* Canonical definitions for peripheral DAPLINK_IF_0_AXI_XIP_QUAD_SPI_0 */
#define XPAR_SPI_3_DEVICE_ID 3U
#define XPAR_SPI_3_BASEADDR 0x40000000U
#define XPAR_SPI_3_HIGHADDR 0x4000FFFFU
#define XPAR_SPI_3_FIFO_DEPTH 16U
#define XPAR_SPI_3_FIFO_EXIST 1U
#define XPAR_SPI_3_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_3_NUM_SS_BITS 1U
#define XPAR_SPI_3_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_3_SPI_MODE 2U
#define XPAR_SPI_3_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_3_AXI4_BASEADDR 0x00000000U
#define XPAR_SPI_3_AXI4_HIGHADDR 0x000FFFFFU
#define XPAR_SPI_3_XIP_MODE 1U
#define XPAR_SPI_3_USE_STARTUP 0U



/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 2

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40100000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4010FFFF
#define XPAR_AXI_UARTLITE_0_DEVICE_ID 0
#define XPAR_AXI_UARTLITE_0_BAUDRATE 115200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 8


/* Definitions for peripheral AXI_UARTLITE_1 */
#define XPAR_AXI_UARTLITE_1_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_1_HIGHADDR 0x4060FFFF
#define XPAR_AXI_UARTLITE_1_DEVICE_ID 1
#define XPAR_AXI_UARTLITE_1_BAUDRATE 115200
#define XPAR_AXI_UARTLITE_1_USE_PARITY 0
#define XPAR_AXI_UARTLITE_1_ODD_PARITY 0
#define XPAR_AXI_UARTLITE_1_DATA_BITS 8


/******************************************************************/

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_AXI_UARTLITE_0_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x40100000
#define XPAR_UARTLITE_0_HIGHADDR 0x4010FFFF
#define XPAR_UARTLITE_0_BAUDRATE 115200
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 8

/* Canonical definitions for peripheral AXI_UARTLITE_1 */
#define XPAR_UARTLITE_1_DEVICE_ID XPAR_AXI_UARTLITE_1_DEVICE_ID
#define XPAR_UARTLITE_1_BASEADDR 0x40600000
#define XPAR_UARTLITE_1_HIGHADDR 0x4060FFFF
#define XPAR_UARTLITE_1_BAUDRATE 115200
#define XPAR_UARTLITE_1_USE_PARITY 0
#define XPAR_UARTLITE_1_ODD_PARITY 0
#define XPAR_UARTLITE_1_DATA_BITS 8


/******************************************************************/

#endif  /* end of protection macro */
