
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 6.7
 PARAMETER PROC_INSTANCE = Cortex_M3_0
 PARAMETER stdin = axi_uartlite_0
 PARAMETER stdout = axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_cortexm3
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Cortex_M3_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_ADC0832
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_ADC0832_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_HeartFre2
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_HeartFre2_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_IO_printer
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_IO_printer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_MAXMIN2
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_MAXMIN2_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_MPU6050_GYXX
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_MPU6050_GYXX_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_StepCounter_debug
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_StepCounter_deb_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_Timer
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_Timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_beep
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_beep_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_dht11
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_dht11_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = axi_bram_ctrl_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = axi_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = axi_gpio_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = axi_gpio_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = axi_quad_spi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = axi_uartlite_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = breath_led
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = breath_led_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = daplink_if_0_axi_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = daplink_if_0_axi_quad_spi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = daplink_if_0_axi_single_spi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = daplink_if_0_axi_xip_quad_spi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_noliner2
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_noliner2_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = Exin_HMITX
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = Exin_HMITX_0
END


